### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by srwgin** [Jasonnor/Granblue-Autotasy#1]
how to use？ thankyou

**Comment by srwgin** [comment]
when coopraid start url change form rom/xxx to raid_multi/xxx 
after I see ready also refresh

**Comment by srwgin** [comment]
if possible separate auto battle and auto enter room

**Comment by Jasonnor** [comment]
Hello there!
This plug-in has not officially released, so I'm not going to write how-to documentation.
Also it's currently a script *tailor-made for* me, maybe you can read the code to rewrite as yours.

For your question,
1. It is a chrome extension, you can packed at extension page.
2. I have fixed the reload problem. (*maybe, need testing*)
